2021-03-24 01:11:27,942 - app.common.log - DEBUG - Thread-2 - Response for get with id request for user {'mobile_number': '9009620167', 'first_name': 'preti', 'id': 14, 'email_id': 'prei@gmail.com', 'last_name': 'sutar', 'address': 'A Nagar'}
2021-03-24 01:11:37,732 - app.common.log - ERROR - Thread-3 - User with this id does not exist
Traceback (most recent call last):
  File "/home/arati/workspace/flask_app/app/views/user.py", line 89, in get
    raise NoResultFound
sqlalchemy.orm.exc.NoResultFound: ()
2021-03-24 01:12:40,943 - app.common.log - INFO - Thread-4 - Response for get request for user list [{'mobile_number': '9504620167', 'first_name': 'prem', 'id': 12, 'email_id': 'sutar@gmail.com', 'last_name': 'sutar', 'address': 'A Nagar'}, {'mobile_number': '9009620167', 'first_name': 'preti', 'id': 14, 'email_id': 'prei@gmail.com', 'last_name': 'sutar', 'address': 'A Nagar'}, {'mobile_number': '9019620167', 'first_name': 'preti', 'id': 15, 'email_id': 'kruti@gmail.com', 'last_name': 'sutar', 'address': 'A Nagar'}]
2021-03-24 01:14:49,920 - app.common.log - INFO - Thread-2 - Response for get request for user list [{'email_id': 'sutar@gmail.com', 'mobile_number': '9504620167', 'address': 'A Nagar', 'first_name': 'prem', 'id': 12, 'last_name': 'sutar'}, {'email_id': 'prei@gmail.com', 'mobile_number': '9009620167', 'address': 'A Nagar', 'first_name': 'preti', 'id': 14, 'last_name': 'sutar'}, {'email_id': 'kruti@gmail.com', 'mobile_number': '9019620167', 'address': 'A Nagar', 'first_name': 'preti', 'id': 15, 'last_name': 'sutar'}]
2021-03-24 01:15:13,838 - app.common.log - INFO - Thread-2 - Response for get request for user list [{'address': 'A Nagar', 'last_name': 'sutar', 'first_name': 'prem', 'id': 12, 'mobile_number': '9504620167', 'email_id': 'sutar@gmail.com'}, {'address': 'A Nagar', 'last_name': 'sutar', 'first_name': 'preti', 'id': 14, 'mobile_number': '9009620167', 'email_id': 'prei@gmail.com'}, {'address': 'A Nagar', 'last_name': 'sutar', 'first_name': 'preti', 'id': 15, 'mobile_number': '9019620167', 'email_id': 'kruti@gmail.com'}]
2021-03-24 01:15:37,278 - app.common.log - ERROR - Thread-3 - User with this id does not exist
Traceback (most recent call last):
  File "/home/arati/workspace/flask_app/app/views/user.py", line 89, in get
    raise NoResultFound
sqlalchemy.orm.exc.NoResultFound: ()
2021-03-24 01:16:33,565 - werkzeug - INFO - MainThread -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2021-03-24 01:16:33,566 - werkzeug - INFO - MainThread -  * Restarting with stat
2021-03-24 01:16:33,957 - werkzeug - WARNING - MainThread -  * Debugger is active!
2021-03-24 01:16:33,957 - werkzeug - INFO - MainThread -  * Debugger PIN: 130-100-764
2021-03-24 01:16:55,296 - root - ERROR - Thread-2 - User with this id does not exist
Traceback (most recent call last):
  File "/home/arati/workspace/flask_app/app/views/user.py", line 89, in get
    raise NoResultFound
sqlalchemy.orm.exc.NoResultFound: ()
2021-03-24 01:16:55,298 - werkzeug - INFO - Thread-2 - 127.0.0.1 - - [24/Mar/2021 01:16:55] "GET /user/144 HTTP/1.1" 404 -
2021-03-24 01:17:39,870 - app.common.log - ERROR - Thread-2 - User with this id does not exist
Traceback (most recent call last):
  File "/home/arati/workspace/flask_app/app/views/user.py", line 89, in get
    raise NoResultFound
sqlalchemy.orm.exc.NoResultFound: ()
2021-03-24 11:53:17,279 - app.common.log - ERROR - Thread-2 - User does not exist
Traceback (most recent call last):
  File "/home/arati/workspace/flask_app/app/views/user.py", line 113, in get
    raise NoResultFound
sqlalchemy.orm.exc.NoResultFound: ()
2021-03-24 11:55:55,778 - app.common.log - ERROR - Thread-4 - User does not exist
Traceback (most recent call last):
  File "/home/arati/workspace/flask_app/app/views/user.py", line 113, in get
    raise NoResultFound
sqlalchemy.orm.exc.NoResultFound: ()
2021-03-24 11:56:02,578 - app.common.log - ERROR - Thread-5 - User type does not exist
Traceback (most recent call last):
  File "/home/arati/workspace/flask_app/app/views/user.py", line 332, in get
    raise NoResultFound
sqlalchemy.orm.exc.NoResultFound: ()
2021-03-24 11:58:34,372 - app.common.log - INFO - Thread-6 - Response for get request for user type list [{'id': 1, 'user_type': 'customer'}, {'id': 2, 'user_type': 'other'}]
2021-03-24 11:58:41,193 - app.common.log - INFO - Thread-7 - Response for get request for user list [{'address': 'pune', 'first_name': 'arati', 'email_id': 'abc@gmail.com', 'id': 1, 'last_name': 'talekar', 'mobile_number': '9503610156'}, {'address': 'mumbai', 'first_name': 'monali', 'email_id': 'mon@gmail.com', 'id': 3, 'last_name': 'mane', 'mobile_number': '9503610157'}]
